name: Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  steps:
      - uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build